GitHub auth
MolSSI-Education/python-package-best-practices pull request #45
Opened 2021-07-14 15:50 UTC by sjayellis

This simply adds the instructions to create a PAT to be used in place of the password.

With just these instructions, users have to type in/copy paste their PAT in place of their password every time. Do we want to cover caching so that the PAT only needs to be entered after a time period has expired or permanently storing the PAT for gits use?

2021-07-14 16:37 UTC, janash commented
> With just these instructions, users have to type in/copy paste their PAT in place of their password every time. Do we want to cover caching so that the PAT only needs to be entered after a time period has expired or permanently storing the PAT for gits use?

I think caching would be a great idea. I understand that PATs are more secure than passwords, but this seems like a giant pain to do with students. Does caching work across repositories and different days? (wondering for the sake of continuity and for when they're working on their own). We might want to expand the explanation of a personal access token a bit more to make it clear when and if they'll have to generate another one.

We could also add information about ssh keys. I think this was in the workshop originally, so you may be able to find instructions if you look way back. However, it was a little bit of a process and I think it was confusing students so I removed it.

2021-07-14 17:04 UTC, sjayellis commented
It is very simple to setup caching for a time period, i.e. it stores the password in memory and will not prompt again for that account for a specified time period. Working across days I think is dependent on the amount of time specified (it is defined in seconds but I dont see a max). For multiple repositories, I believe all git will care about is that you are connecting via the same account. So if your git is configured with 1 account and that account has permissions on both repositories I believe it will work fine.

As far as generating more keys, you really only need to have multiple if you want to have different permissions for them. I.e. you can setup one that just handles commits/pushes/ etc. And a different one that has access to github actions workflows. This allows some granularity of permissions, but I think that is a bit beyond the scope of the workshop. Though it occurs to me we do use github actions so I need to make a quick change to the setup instructions. I can add the simple commands to setup timed caching as well. I am not sure if we want to set up permenant caching for them as they has larger security concerns that I am not sure we want to get into.

2021-07-14 18:00 UTC, janash commented
> As far as generating more keys, you really only need to have multiple if you want to have different permissions for them. I.e. you can setup one that just handles commits/pushes/ etc. 

Sure, yes I understand this. However, it only shows you this once, so if your cache expires and you haven't saved it somewhere, you'll have to generate another (and probably remove the previous one). Should we tell them to save it somewhere?

2021-07-14 18:04 UTC, sjayellis commented
That is true. It leaves us in an awkward spot because they can either save it themselves somewhere or they can have git save it in a file for them. Neither is honestly a good option.

2021-07-14 18:19 UTC, radifar commented
Looks good to me, there are some typos but we can fix that later. One question though:

`git config --global credential.helper 'cache --timeout=3600'`
Is this command also apply in MacOS? Since the MacOS use osxkeychain. So I thought that probably the command would be different in MacOS.

> Sure, yes I understand this. However, it only shows you this once, so if your cache expires and you haven't saved it somewhere, you'll have to generate another (and probably remove the previous one). Should we tell them to save it somewhere?

I've been using PAT for some few weeks now. And so far I've been thinking the same. The easiest way would be to store the PAT in simple text file, which is what I've doing until now. The other is probably by putting the PAT in environment variable and echo that variable every time we need it. I haven't tried the latter though.

2021-07-14 18:27 UTC, radifar commented
Oh, and one more thing. Perhaps this instruction can be moved to a new section rather than inside the **Create GitHub Account** section? For example we can put them in new section called **Setting Up Your Personal Account Token**.

2021-07-14 18:30 UTC, sjayellis commented
Upon further reading of the [Git credentials docs](https://git-scm.com/book/en/v2/Git-Tools-Credential-Storage), I believe the osxkeychain tool acts as a permanent store but is encrypted so there is no caching. I will shift the command to only be for the linux/WSL.

For Linux/WSL, they can either store the PAT in a file in plain text, or can have git setup to store and automatically utilize the PAT, also from a plain text file, using the store command.
```
git config --global credential.helper 'store --file ~/.my-credentials'
```

2021-07-16 13:25 UTC, eirrgang requested changes

2021-07-16 13:25 UTC, eirrgang commented on setup.md
> +To utilize github from the command line, you will need to generate a Personal Access Token (PAT).
```suggestion
To utilize github from the command line, you will need to
[provide GitHub with an SSH public key](https://docs.github.com/en/github/authenticating-to-github/connecting-to-github-with-ssh)
or generate a GitHub Personal Access Token (PAT).


```

2021-07-18 13:54 UTC, eirrgang approved these changes
I'm really skeptical of this PAT thing. It seems complicated and non-normative compared to ssh keys, which people are presumably already using (or will be using) for HPC system access.

> The easiest way would be to store the PAT in simple text file, which is what I've been doing until now. The other is probably by putting the PAT in environment variable and echo that variable every time we need it. I haven't tried the latter though.

Both of these sound like really bad options for a shared system, like an HPC login node. (Even less secure than the http authentication that GitHub wanted to move away from :-\ )

I'll be interested to hear whether the PAT turns out to be easier than ssh keys in future workshops.

2021-07-18 13:54 UTC, eirrgang commented on setup.md
> +This can become tedius if you are making multiple pushes over a short period.
```suggestion
This can become tedious if you are making multiple pushes over a short period.
```

2021-07-18 13:54 UTC, eirrgang commented on setup.md
> +to setup caching for your operating system.
```suggestion
to set up caching for your operating system.
```

2021-07-20 23:59 UTC, janash commented on setup.md
```suggestion
You should next set the default branch name you will work on. Branches will be explained in detail later. This configuration setting makes the default branch name match the default branch name on GitHub

~~~
git config --global init.defaultBranch main
~~~
{: .bash}

```

2021-07-21 00:03 UTC, janash requested changes
Hi @sjayellis - I can't figure out how to add a comment on some of the lines which have not been edit. I think we should upgrade the Python version in the environment to Python 3.9 (so on the `conda create` command on line 86, please change it to `python=3.9`. This won't have any noticeable difference that I'm aware of for the workshop.

Please also change the `conda install git` command on line 195 to `conda install -c conda-forge git` this will install git version 2.32.0. The command in the current set-up may result in installation for the conda channel where git is only 2.23. I'm not exactly sure that it will, but it's better to be explicit.

Git 2.23.0 doesn't have the option to set the default branch, which I've added as a suggestion later.

2021-07-21 14:29 UTC, sjayellis commented
I am similarly a bit concerned with the PATs. I understand the security gains from them over passwords. You can specify a PAT to have different permissions across your GitHub account, such as pushing to repos, handling github actions, etc. Whereas a password covers everything. I think in this case a ssh key is similar to a password in that a single one has permissions across your account but I am not positive on that, please correct me if I am wrong.

So I see the benfits, but the fact that git does not have an easy way to encrypt them and store them (outside of the macos version at the moment) makes me concerned about their security. Combined with the fact that it would be difficult to memorize the PAT, so it is likely written down somewhere seems like a glaring problem with the system.

2021-07-21 14:32 UTC, sjayellis commented
Upon some further searching there is a credential manager for Windows that, similar to osxkeychain, will encrypt your credentials locally, but I am not seeing a direct one for linux.

2021-07-22 03:12 UTC, radifar commented
I'm gonna add these as a reference for various alternatives that we can use to store credential in Windows and Linux:
1. [Where to store the personal access token from GitHub?](https://stackoverflow.com/questions/46645843/where-to-store-the-personal-access-token-from-github)
2. [Git Credential Manager Core](https://github.com/microsoft/Git-Credential-Manager-Core/)
3. [Libsecret - remember Git credentials in Linux Mint and Ubuntu securely](https://www.softwaredeveloper.blog/git-credential-storage-libsecret)

2021-07-30 18:55 UTC, janash approved these changes
This looks good to me. I just added one final sentence to be extra clear that they should click the link and follow the instructions.

2021-07-30 18:55 UTC, janash commented on setup.md
> +The linked documentation provides information about SSH keys, how to find out if you already have an SSH key, and how to generate and add one to your GitHub account.
```suggestion
The linked documentation provides information about SSH keys, how to find out if you already have an SSH key, and how to generate and add one to your GitHub account. 
You should click the link and follow the instructions to add an SSH key to your GitHub account.
```

2021-07-30 18:57 UTC, merged