first pass on 07-testing
MolSSI-Education/python-package-best-practices pull request #50
Opened 2021-07-20 05:18 UTC by radifar

Added new lines in every end of sentence. Fix few typos.

2021-07-22 12:56 UTC, eirrgang requested changes

2021-07-22 12:56 UTC, eirrgang commented on _episodes/07-testing.md
> +It is considered good practices to also break your tests into different files depending on the module or subpackage.
```suggestion
It is considered good practice to also break your tests into different files depending on the module or subpackage.
```

2021-07-22 12:56 UTC, eirrgang commented on _episodes/07-testing.md
> +We could add our own mark
```suggestion
We could add our own mark:
```

2021-07-22 16:48 UTC, eirrgang commented
Relates to https://github.com/MolSSI-Education/python-package-best-practices/pull/13

2021-08-02 03:11 UTC, janash reviewed
Looks good as a first pass. Is it ready to merge?

2021-08-02 03:11 UTC, janash commented on _episodes/07-testing.md
> +In Regression tests, given a known input, does the software correctly and consistently return the correct values?
```suggestion
In Regression tests, given a known input, does the software correctly and consistently return the correct values.
```

2021-08-03 12:46 UTC, radifar commented on _episodes/07-testing.md
> +In Regression tests, given a known input, does the software correctly and consistently return the correct values?
Sorry, missed this one.

2021-08-03 12:46 UTC, radifar commented
OK, ready to merge.

2021-08-03 13:28 UTC, janash approved these changes

2021-08-03 13:28 UTC, merged